// WC 2026 Kadroları — 48 Takım
// pos: GK=Kaleci, DEF=Defans, MID=Orta Saha, FWD=Forvet
const WC2026_SQUADS = {
  tr: { name: 'Türkiye', flag: 'tr', players: [
    { id: 'tr1',  name: 'Altay Bayındır',   pos: 'GK',  club: 'Manchester United',   no: 1  },
    { id: 'tr2',  name: 'Uğurcan Çakır',    pos: 'GK',  club: 'Trabzonspor',         no: 12 },
    { id: 'tr3',  name: 'Mert Günok',       pos: 'GK',  club: 'Beşiktaş',            no: 23 },
    { id: 'tr4',  name: 'Samet Akaydın',    pos: 'DEF', club: 'Fenerbahçe',          no: 3  },
    { id: 'tr5',  name: 'Merih Demiral',    pos: 'DEF', club: 'Al-Qadsiah',          no: 4  },
    { id: 'tr6',  name: 'Çağlar Söyüncü',   pos: 'DEF', club: 'Fenerbahçe',          no: 5  },
    { id: 'tr7',  name: 'Ferdi Kadıoğlu',   pos: 'DEF', club: 'Brighton',            no: 2  },
    { id: 'tr8',  name: 'Zeki Çelik',       pos: 'DEF', club: 'Roma',                no: 22 },
    { id: 'tr9',  name: 'Mert Müldür',      pos: 'DEF', club: 'Sassuolo',            no: 17 },
    { id: 'tr10', name: 'Kaan Ayhan',       pos: 'DEF', club: 'Galatasaray',         no: 15 },
    { id: 'tr11', name: 'Hakan Çalhanoğlu', pos: 'MID', club: 'Inter Milan',         no: 8  },
    { id: 'tr12', name: 'Salih Özcan',      pos: 'MID', club: 'Borussia Dortmund',   no: 6  },
    { id: 'tr13', name: 'Okay Yokuşlu',     pos: 'MID', club: 'Swansea City',        no: 16 },
    { id: 'tr14', name: 'İsmail Yüksek',    pos: 'MID', club: 'Fenerbahçe',          no: 20 },
    { id: 'tr15', name: 'Arda Güler',       pos: 'MID', club: 'Real Madrid',         no: 10 },
    { id: 'tr16', name: 'Kenan Yıldız',     pos: 'MID', club: 'Juventus',            no: 11 },
    { id: 'tr17', name: 'Barış Alper Yılmaz', pos: 'FWD', club: 'Galatasaray',       no: 7  },
    { id: 'tr18', name: 'Cenk Tosun',       pos: 'FWD', club: 'Beşiktaş',            no: 9  },
    { id: 'tr19', name: 'Yusuf Yazıcı',     pos: 'MID', club: 'LOSC Lille',          no: 14 },
    { id: 'tr20', name: 'Muhammed Şahin',   pos: 'MID', club: 'Fenerbahçe',          no: 13 },
    { id: 'tr21', name: 'Emirhan İlkhan',   pos: 'MID', club: 'Trabzonspor',         no: 19 },
    { id: 'tr22', name: 'Serdar Dursun',    pos: 'FWD', club: 'Darmstadt',           no: 21 },
    { id: 'tr23', name: 'Cengiz Ünder',     pos: 'FWD', club: 'Fenerbahçe',          no: 18 },
  ]},
  de: { name: 'Almanya', flag: 'de', players: [
    { id: 'de1',  name: 'Manuel Neuer',     pos: 'GK',  club: 'Bayern München',      no: 1  },
    { id: 'de2',  name: 'Marc-André ter Stegen', pos: 'GK', club: 'Barcelona',       no: 12 },
    { id: 'de3',  name: 'Antonio Rüdiger',  pos: 'DEF', club: 'Real Madrid',         no: 2  },
    { id: 'de4',  name: 'Nico Schlotterbeck', pos: 'DEF', club: 'Borussia Dortmund', no: 3  },
    { id: 'de5',  name: 'Jonathan Tah',     pos: 'DEF', club: 'Bayern München',      no: 4  },
    { id: 'de6',  name: 'Joshua Kimmich',   pos: 'MID', club: 'Bayern München',      no: 6  },
    { id: 'de7',  name: 'İlkay Gündoğan',   pos: 'MID', club: 'Barcelona',           no: 21 },
    { id: 'de8',  name: 'Florian Wirtz',    pos: 'MID', club: 'Bayern München',      no: 10 },
    { id: 'de9',  name: 'Jamal Musiala',    pos: 'MID', club: 'Bayern München',      no: 14 },
    { id: 'de10', name: 'Leroy Sané',       pos: 'FWD', club: 'Bayern München',      no: 19 },
    { id: 'de11', name: 'Kai Havertz',      pos: 'FWD', club: 'Arsenal',             no: 9  },
    { id: 'de12', name: 'Niclas Füllkrug',  pos: 'FWD', club: 'West Ham',            no: 11 },
    { id: 'de13', name: 'Thomas Müller',    pos: 'FWD', club: 'Bayern München',      no: 13 },
    { id: 'de14', name: 'David Raum',       pos: 'DEF', club: 'RB Leipzig',          no: 5  },
    { id: 'de15', name: 'Robert Andrich',   pos: 'MID', club: 'Bayer Leverkusen',    no: 23 },
    { id: 'de16', name: 'Leon Goretzka',    pos: 'MID', club: 'Bayern München',      no: 8  },
    { id: 'de17', name: 'Chris Führich',    pos: 'FWD', club: 'VfB Stuttgart',       no: 17 },
    { id: 'de18', name: 'Deniz Undav',      pos: 'FWD', club: 'VfB Stuttgart',       no: 18 },
    { id: 'de19', name: 'Maximilian Mittelstädt', pos: 'DEF', club: 'VfB Stuttgart', no: 7  },
    { id: 'de20', name: 'Benjamin Henrichs', pos: 'DEF', club: 'RB Leipzig',         no: 20 },
    { id: 'de21', name: 'Emre Can',         pos: 'MID', club: 'Borussia Dortmund',   no: 22 },
    { id: 'de22', name: 'Alexander Nübel',  pos: 'GK',  club: 'VfB Stuttgart',       no: 16 },
  ]},
  br: { name: 'Brezilya', flag: 'br', players: [
    { id: 'br1',  name: 'Alisson',          pos: 'GK',  club: 'Liverpool',           no: 1  },
    { id: 'br2',  name: 'Ederson',          pos: 'GK',  club: 'Manchester City',     no: 23 },
    { id: 'br3',  name: 'Éder Militão',     pos: 'DEF', club: 'Real Madrid',         no: 3  },
    { id: 'br4',  name: 'Marquinhos',       pos: 'DEF', club: 'PSG',                 no: 4  },
    { id: 'br5',  name: 'Danilo',           pos: 'DEF', club: 'Juventus',            no: 2  },
    { id: 'br6',  name: 'Alex Telles',      pos: 'DEF', club: 'Sevilla',             no: 6  },
    { id: 'br7',  name: 'Casemiro',         pos: 'MID', club: 'Manchester United',   no: 5  },
    { id: 'br8',  name: 'Lucas Paquetá',    pos: 'MID', club: 'West Ham',            no: 10 },
    { id: 'br9',  name: 'Bruno Guimarães',  pos: 'MID', club: 'Newcastle',           no: 17 },
    { id: 'br10', name: 'Rodrygo',          pos: 'FWD', club: 'Real Madrid',         no: 11 },
    { id: 'br11', name: 'Vinicius Jr.',     pos: 'FWD', club: 'Real Madrid',         no: 7  },
    { id: 'br12', name: 'Raphinha',         pos: 'FWD', club: 'Barcelona',           no: 19 },
    { id: 'br13', name: 'Gabriel Martinelli', pos: 'FWD', club: 'Arsenal',           no: 21 },
    { id: 'br14', name: 'Antony',           pos: 'FWD', club: 'Manchester United',   no: 20 },
    { id: 'br15', name: 'Gabriel Jesus',    pos: 'FWD', club: 'Arsenal',             no: 9  },
    { id: 'br16', name: 'Endrick',          pos: 'FWD', club: 'Real Madrid',         no: 15 },
    { id: 'br17', name: 'Thiago Silva',     pos: 'DEF', club: 'Fluminense',          no: 14 },
    { id: 'br18', name: 'Renan Lodi',       pos: 'DEF', club: 'Flamengo',            no: 8  },
    { id: 'br19', name: 'Fred',             pos: 'MID', club: 'Manchester United',   no: 13 },
    { id: 'br20', name: 'Richarlison',      pos: 'FWD', club: 'Tottenham',           no: 18 },
    { id: 'br21', name: 'Gabriel Magalhães', pos: 'DEF', club: 'Arsenal',            no: 22 },
    { id: 'br22', name: 'Weverton',         pos: 'GK',  club: 'Palmeiras',           no: 12 },
  ]},
  ar: { name: 'Arjantin', flag: 'ar', players: [
    { id: 'ar1',  name: 'Emiliano Martínez', pos: 'GK', club: 'Aston Villa',         no: 23 },
    { id: 'ar2',  name: 'Franco Armani',    pos: 'GK',  club: 'River Plate',         no: 1  },
    { id: 'ar3',  name: 'Lionel Messi',     pos: 'FWD', club: 'Inter Miami',         no: 10 },
    { id: 'ar4',  name: 'Lautaro Martínez', pos: 'FWD', club: 'Inter Milan',         no: 22 },
    { id: 'ar5',  name: 'Julián Álvarez',   pos: 'FWD', club: 'Atlético Madrid',     no: 9  },
    { id: 'ar6',  name: 'Ángel Di María',   pos: 'FWD', club: 'Benfica',             no: 11 },
    { id: 'ar7',  name: 'Rodrigo De Paul',  pos: 'MID', club: 'Atlético Madrid',     no: 7  },
    { id: 'ar8',  name: 'Alexis Mac Allister', pos: 'MID', club: 'Liverpool',        no: 20 },
    { id: 'ar9',  name: 'Enzo Fernández',   pos: 'MID', club: 'Chelsea',             no: 24 },
    { id: 'ar10', name: 'Nicolás Otamendi', pos: 'DEF', club: 'Benfica',             no: 19 },
    { id: 'ar11', name: 'Cristian Romero',  pos: 'DEF', club: 'Tottenham',           no: 13 },
    { id: 'ar12', name: 'Nahuel Molina',    pos: 'DEF', club: 'Atlético Madrid',     no: 26 },
    { id: 'ar13', name: 'Marcos Acuña',     pos: 'DEF', club: 'Sevilla',             no: 8  },
    { id: 'ar14', name: 'Nicolás Tagliafico', pos: 'DEF', club: 'Lyon',              no: 3  },
    { id: 'ar15', name: 'Leandro Paredes',  pos: 'MID', club: 'Roma',                no: 5  },
    { id: 'ar16', name: 'Giovani Lo Celso', pos: 'MID', club: 'Villarreal',          no: 14 },
    { id: 'ar17', name: 'Paulo Dybala',     pos: 'FWD', club: 'Roma',                no: 21 },
    { id: 'ar18', name: 'Germán Pezzella',  pos: 'DEF', club: 'Real Betis',          no: 6  },
    { id: 'ar19', name: 'Thiago Almada',    pos: 'MID', club: 'Lyon',                no: 18 },
    { id: 'ar20', name: 'Alejandro Garnacho', pos: 'FWD', club: 'Manchester United', no: 17 },
    { id: 'ar21', name: 'Geronimo Rulli',   pos: 'GK',  club: 'Ajax',                no: 12 },
  ]},
  fr: { name: 'Fransa', flag: 'fr', players: [
    { id: 'fr1',  name: 'Mike Maignan',     pos: 'GK',  club: 'AC Milan',            no: 16 },
    { id: 'fr2',  name: 'Hugo Lloris',      pos: 'GK',  club: 'Los Angeles FC',      no: 1  },
    { id: 'fr3',  name: 'Kylian Mbappé',    pos: 'FWD', club: 'Real Madrid',         no: 10 },
    { id: 'fr4',  name: 'Antoine Griezmann', pos: 'FWD', club: 'Atlético Madrid',    no: 7  },
    { id: 'fr5',  name: 'Ousmane Dembélé',  pos: 'FWD', club: 'PSG',                 no: 11 },
    { id: 'fr6',  name: 'Olivier Giroud',   pos: 'FWD', club: 'Los Angeles FC',      no: 9  },
    { id: 'fr7',  name: 'N\'Golo Kanté',    pos: 'MID', club: 'Al-Ittihad',          no: 13 },
    { id: 'fr8',  name: 'Aurélien Tchouaméni', pos: 'MID', club: 'Real Madrid',      no: 8  },
    { id: 'fr9',  name: 'Adrien Rabiot',    pos: 'MID', club: 'Juventus',            no: 14 },
    { id: 'fr10', name: 'Raphaël Varane',   pos: 'DEF', club: 'Como',                no: 4  },
    { id: 'fr11', name: 'Dayot Upamecano',  pos: 'DEF', club: 'Bayern München',      no: 5  },
    { id: 'fr12', name: 'Theo Hernández',   pos: 'DEF', club: 'AC Milan',            no: 22 },
    { id: 'fr13', name: 'Benjamin Pavard',  pos: 'DEF', club: 'Inter Milan',         no: 2  },
    { id: 'fr14', name: 'Jules Koundé',     pos: 'DEF', club: 'Barcelona',           no: 21 },
    { id: 'fr15', name: 'Marcus Thuram',    pos: 'FWD', club: 'Inter Milan',         no: 15 },
    { id: 'fr16', name: 'Randal Kolo Muani', pos: 'FWD', club: 'Juventus',           no: 19 },
    { id: 'fr17', name: 'Eduardo Camavinga', pos: 'MID', club: 'Real Madrid',        no: 6  },
    { id: 'fr18', name: 'Youssouf Fofana',  pos: 'MID', club: 'AC Milan',            no: 17 },
    { id: 'fr19', name: 'William Saliba',   pos: 'DEF', club: 'Arsenal',             no: 17 },
    { id: 'fr20', name: 'Kingsley Coman',   pos: 'FWD', club: 'Bayern München',      no: 20 },
    { id: 'fr21', name: 'Alphonse Aréola',  pos: 'GK',  club: 'West Ham',            no: 23 },
  ]},
  es: { name: 'İspanya', flag: 'es', players: [
    { id: 'es1',  name: 'Unai Simón',       pos: 'GK',  club: 'Athletic Bilbao',     no: 23 },
    { id: 'es2',  name: 'David Raya',       pos: 'GK',  club: 'Arsenal',             no: 1  },
    { id: 'es3',  name: 'Rodri',            pos: 'MID', club: 'Manchester City',     no: 16 },
    { id: 'es4',  name: 'Lamine Yamal',     pos: 'FWD', club: 'Barcelona',           no: 19 },
    { id: 'es5',  name: 'Pedri',            pos: 'MID', club: 'Barcelona',           no: 8  },
    { id: 'es6',  name: 'Gavi',             pos: 'MID', club: 'Barcelona',           no: 6  },
    { id: 'es7',  name: 'Dani Olmo',        pos: 'MID', club: 'Barcelona',           no: 10 },
    { id: 'es8',  name: 'Álvaro Morata',    pos: 'FWD', club: 'AC Milan',            no: 7  },
    { id: 'es9',  name: 'Nico Williams',    pos: 'FWD', club: 'Athletic Bilbao',     no: 11 },
    { id: 'es10', name: 'Mikel Merino',     pos: 'MID', club: 'Arsenal',             no: 22 },
    { id: 'es11', name: 'Fabián Ruiz',      pos: 'MID', club: 'PSG',                 no: 14 },
    { id: 'es12', name: 'Aymeric Laporte',  pos: 'DEF', club: 'Al-Nassr',            no: 14 },
    { id: 'es13', name: 'Dani Carvajal',    pos: 'DEF', club: 'Real Madrid',         no: 2  },
    { id: 'es14', name: 'Alejandro Grimaldo', pos: 'DEF', club: 'Bayer Leverkusen',  no: 3  },
    { id: 'es15', name: 'Robin Le Normand', pos: 'DEF', club: 'Atlético Madrid',     no: 5  },
    { id: 'es16', name: 'Nacho Fernández',  pos: 'DEF', club: 'Al-Qadsiah',          no: 4  },
    { id: 'es17', name: 'Mikel Oyarzabal',  pos: 'FWD', club: 'Real Sociedad',       no: 17 },
    { id: 'es18', name: 'Fermin López',     pos: 'MID', club: 'Barcelona',           no: 21 },
    { id: 'es19', name: 'Joselu',           pos: 'FWD', club: 'Real Madrid',         no: 9  },
    { id: 'es20', name: 'Marc Cucurella',   pos: 'DEF', club: 'Chelsea',             no: 24 },
    { id: 'es21', name: 'Pau Cubarsí',      pos: 'DEF', club: 'Barcelona',           no: 26 },
  ]},
  en: { name: 'İngiltere', flag: 'gb-eng', players: [
    { id: 'en1',  name: 'Jordan Pickford',  pos: 'GK',  club: 'Everton',             no: 1  },
    { id: 'en2',  name: 'Aaron Ramsdale',   pos: 'GK',  club: 'Southampton',         no: 23 },
    { id: 'en3',  name: 'Harry Kane',       pos: 'FWD', club: 'Bayern München',      no: 9  },
    { id: 'en4',  name: 'Jude Bellingham',  pos: 'MID', club: 'Real Madrid',         no: 10 },
    { id: 'en5',  name: 'Phil Foden',       pos: 'MID', club: 'Manchester City',     no: 20 },
    { id: 'en6',  name: 'Bukayo Saka',      pos: 'FWD', club: 'Arsenal',             no: 7  },
    { id: 'en7',  name: 'Declan Rice',      pos: 'MID', club: 'Arsenal',             no: 4  },
    { id: 'en8',  name: 'Trent Alexander-Arnold', pos: 'DEF', club: 'Real Madrid',   no: 2  },
    { id: 'en9',  name: 'Luke Shaw',        pos: 'DEF', club: 'Manchester United',   no: 3  },
    { id: 'en10', name: 'John Stones',      pos: 'DEF', club: 'Manchester City',     no: 5  },
    { id: 'en11', name: 'Harry Maguire',    pos: 'DEF', club: 'Manchester United',   no: 6  },
    { id: 'en12', name: 'Kyle Walker',      pos: 'DEF', club: 'Manchester City',     no: 2  },
    { id: 'en13', name: 'Marcus Rashford',  pos: 'FWD', club: 'Manchester United',   no: 11 },
    { id: 'en14', name: 'Jack Grealish',    pos: 'FWD', club: 'Manchester City',     no: 22 },
    { id: 'en15', name: 'Cole Palmer',      pos: 'MID', club: 'Chelsea',             no: 24 },
    { id: 'en16', name: 'Kobbie Mainoo',    pos: 'MID', club: 'Manchester United',   no: 26 },
    { id: 'en17', name: 'Ollie Watkins',    pos: 'FWD', club: 'Aston Villa',         no: 19 },
    { id: 'en18', name: 'Conor Gallagher',  pos: 'MID', club: 'Atlético Madrid',     no: 14 },
    { id: 'en19', name: 'Ezri Konsa',       pos: 'DEF', club: 'Aston Villa',         no: 16 },
    { id: 'en20', name: 'Marc Guéhi',       pos: 'DEF', club: 'Crystal Palace',      no: 18 },
    { id: 'en21', name: 'Anthony Gordon',   pos: 'FWD', club: 'Newcastle',           no: 25 },
    { id: 'en22', name: 'Dean Henderson',   pos: 'GK',  club: 'Crystal Palace',      no: 13 },
  ]},
  pt: { name: 'Portekiz', flag: 'pt', players: [
    { id: 'pt1',  name: 'Diogo Costa',      pos: 'GK',  club: 'Porto',               no: 1  },
    { id: 'pt2',  name: 'Rui Patrício',     pos: 'GK',  club: 'Roma',                no: 12 },
    { id: 'pt3',  name: 'Cristiano Ronaldo', pos: 'FWD', club: 'Al-Nassr',           no: 7  },
    { id: 'pt4',  name: 'Bruno Fernandes',  pos: 'MID', club: 'Manchester United',   no: 8  },
    { id: 'pt5',  name: 'Bernardo Silva',   pos: 'MID', club: 'Manchester City',     no: 10 },
    { id: 'pt6',  name: 'Rafael Leão',      pos: 'FWD', club: 'AC Milan',            no: 11 },
    { id: 'pt7',  name: 'Rúben Dias',       pos: 'DEF', club: 'Manchester City',     no: 4  },
    { id: 'pt8',  name: 'Pepe',             pos: 'DEF', club: 'Porto',               no: 3  },
    { id: 'pt9',  name: 'João Cancelo',     pos: 'DEF', club: 'Barcelona',           no: 20 },
    { id: 'pt10', name: 'Nuno Mendes',      pos: 'DEF', club: 'PSG',                 no: 19 },
    { id: 'pt11', name: 'William Carvalho', pos: 'MID', club: 'Real Betis',          no: 14 },
    { id: 'pt12', name: 'Vitinha',          pos: 'MID', club: 'PSG',                 no: 13 },
    { id: 'pt13', name: 'João Neves',       pos: 'MID', club: 'PSG',                 no: 26 },
    { id: 'pt14', name: 'Diogo Dalot',      pos: 'DEF', club: 'Manchester United',   no: 2  },
    { id: 'pt15', name: 'António Silva',    pos: 'DEF', club: 'Benfica',             no: 6  },
    { id: 'pt16', name: 'Pedro Neto',       pos: 'FWD', club: 'Chelsea',             no: 17 },
    { id: 'pt17', name: 'João Félix',       pos: 'FWD', club: 'Barcelona',           no: 21 },
    { id: 'pt18', name: 'Gonçalo Ramos',    pos: 'FWD', club: 'PSG',                 no: 9  },
    { id: 'pt19', name: 'Matheus Nunes',    pos: 'MID', club: 'Manchester City',     no: 24 },
    { id: 'pt20', name: 'Gonçalo Inácio',   pos: 'DEF', club: 'Sporting CP',         no: 5  },
    { id: 'pt21', name: 'Francisco Conceição', pos: 'FWD', club: 'Juventus',         no: 25 },
  ]},
  nl: { name: 'Hollanda', flag: 'nl', players: [
    { id: 'nl1',  name: 'Bart Verbruggen',  pos: 'GK',  club: 'Brighton',            no: 1  },
    { id: 'nl2',  name: 'Mark Flekken',     pos: 'GK',  club: 'Brentford',           no: 12 },
    { id: 'nl3',  name: 'Virgil van Dijk',  pos: 'DEF', club: 'Liverpool',           no: 4  },
    { id: 'nl4',  name: 'Matthijs de Ligt', pos: 'DEF', club: 'Manchester United',   no: 3  },
    { id: 'nl5',  name: 'Stefan de Vrij',   pos: 'DEF', club: 'Inter Milan',         no: 6  },
    { id: 'nl6',  name: 'Denzel Dumfries',  pos: 'DEF', club: 'Inter Milan',         no: 22 },
    { id: 'nl7',  name: 'Nathan Aké',       pos: 'DEF', club: 'Manchester City',     no: 5  },
    { id: 'nl8',  name: 'Frenkie de Jong',  pos: 'MID', club: 'Barcelona',           no: 21 },
    { id: 'nl9',  name: 'Tijjani Reijnders', pos: 'MID', club: 'AC Milan',           no: 14 },
    { id: 'nl10', name: 'Xavi Simons',      pos: 'MID', club: 'RB Leipzig',          no: 10 },
    { id: 'nl11', name: 'Memphis Depay',    pos: 'FWD', club: 'Atlético Madrid',     no: 10 },
    { id: 'nl12', name: 'Cody Gakpo',       pos: 'FWD', club: 'Liverpool',           no: 11 },
    { id: 'nl13', name: 'Wout Weghorst',    pos: 'FWD', club: 'Hoffenheim',          no: 19 },
    { id: 'nl14', name: 'Steven Bergwijn',  pos: 'FWD', club: 'Ajax',                no: 7  },
    { id: 'nl15', name: 'Davy Klaassen',    pos: 'MID', club: 'Ajax',                no: 8  },
    { id: 'nl16', name: 'Teun Koopmeiners', pos: 'MID', club: 'Juventus',            no: 15 },
    { id: 'nl17', name: 'Lutsharel Geertruida', pos: 'DEF', club: 'RB Leipzig',      no: 2  },
    { id: 'nl18', name: 'Brian Brobbey',    pos: 'FWD', club: 'Ajax',                no: 9  },
    { id: 'nl19', name: 'Donyell Malen',    pos: 'FWD', club: 'Borussia Dortmund',   no: 18 },
    { id: 'nl20', name: 'Joey Veerman',     pos: 'MID', club: 'PSV Eindhoven',       no: 17 },
    { id: 'nl21', name: 'Ryan Gravenberch', pos: 'MID', club: 'Liverpool',           no: 16 },
  ]},
  hr: { name: 'Hırvatistan', flag: 'hr', players: [
    { id: 'hr1',  name: 'Dominik Livaković', pos: 'GK', club: 'Fenerbahçe',         no: 1  },
    { id: 'hr2',  name: 'Luka Modrić',      pos: 'MID', club: 'Real Madrid',         no: 10 },
    { id: 'hr3',  name: 'Mateo Kovačić',    pos: 'MID', club: 'Manchester City',     no: 8  },
    { id: 'hr4',  name: 'Marcelo Brozović', pos: 'MID', club: 'Al-Nassr',            no: 11 },
    { id: 'hr5',  name: 'Ivan Perišić',     pos: 'FWD', club: 'Hajduk Split',        no: 4  },
    { id: 'hr6',  name: 'Ante Budimir',     pos: 'FWD', club: 'Osasuna',             no: 9  },
    { id: 'hr7',  name: 'Joško Gvardiol',   pos: 'DEF', club: 'Manchester City',     no: 3  },
    { id: 'hr8',  name: 'Dejan Lovren',     pos: 'DEF', club: 'Zenit',               no: 6  },
    { id: 'hr9',  name: 'Josip Stanišić',   pos: 'DEF', club: 'Bayer Leverkusen',    no: 2  },
    { id: 'hr10', name: 'Borna Sosa',       pos: 'DEF', club: 'Ajax',                no: 21 },
    { id: 'hr11', name: 'Andrej Kramarić',  pos: 'FWD', club: 'Hoffenheim',          no: 16 },
    { id: 'hr12', name: 'Bruno Petković',   pos: 'FWD', club: 'Dinamo Zagreb',       no: 17 },
    { id: 'hr13', name: 'Mario Pašalić',    pos: 'MID', club: 'Atalanta',            no: 19 },
    { id: 'hr14', name: 'Lovro Majer',      pos: 'MID', club: 'Rennes',              no: 22 },
    { id: 'hr15', name: 'Nikola Vlašić',    pos: 'MID', club: 'Torino',              no: 13 },
    { id: 'hr16', name: 'Martin Erlic',     pos: 'DEF', club: 'Sassuolo',            no: 5  },
    { id: 'hr17', name: 'Domagoj Vida',     pos: 'DEF', club: 'AEK Athens',          no: 7  },
    { id: 'hr18', name: 'Ivica Ivušić',     pos: 'GK',  club: 'Osasuna',             no: 23 },
    { id: 'hr19', name: 'Mislav Oršić',     pos: 'FWD', club: 'Celta Vigo',          no: 18 },
    { id: 'hr20', name: 'Luka Sučić',       pos: 'MID', club: 'RB Salzburg',         no: 20 },
  ]},
  be: { name: 'Belçika', flag: 'be', players: [
    { id: 'be1',  name: 'Thibaut Courtois', pos: 'GK',  club: 'Real Madrid',         no: 1  },
    { id: 'be2',  name: 'Kevin De Bruyne',  pos: 'MID', club: 'Manchester City',     no: 7  },
    { id: 'be3',  name: 'Romelu Lukaku',    pos: 'FWD', club: 'Roma',                no: 9  },
    { id: 'be4',  name: 'Eden Hazard',      pos: 'FWD', club: 'Emretired',           no: 10 },
    { id: 'be5',  name: 'Youri Tielemans',  pos: 'MID', club: 'Aston Villa',         no: 8  },
    { id: 'be6',  name: 'Axel Witsel',      pos: 'MID', club: 'Atlético Madrid',     no: 6  },
    { id: 'be7',  name: 'Jan Vertonghen',   pos: 'DEF', club: 'Anderlecht',          no: 5  },
    { id: 'be8',  name: 'Toby Alderweireld', pos: 'DEF', club: 'Antwerp',            no: 4  },
    { id: 'be9',  name: 'Thomas Meunier',   pos: 'DEF', club: 'Trabzonspor',         no: 2  },
    { id: 'be10', name: 'Leandro Trossard', pos: 'FWD', club: 'Arsenal',             no: 11 },
    { id: 'be11', name: 'Charles De Ketelaere', pos: 'MID', club: 'Atalanta',        no: 14 },
    { id: 'be12', name: 'Amadou Onana',     pos: 'MID', club: 'Aston Villa',         no: 22 },
    { id: 'be13', name: 'Arthur Theate',    pos: 'DEF', club: 'Rennes',              no: 3  },
    { id: 'be14', name: 'Wout Faes',        pos: 'DEF', club: 'Leicester City',      no: 15 },
    { id: 'be15', name: 'Dodi Lukebakio',   pos: 'FWD', club: 'Sevilla',             no: 17 },
    { id: 'be16', name: 'Lois Openda',      pos: 'FWD', club: 'RB Leipzig',          no: 19 },
    { id: 'be17', name: 'Timothy Castagne', pos: 'DEF', club: 'Fulham',              no: 24 },
    { id: 'be18', name: 'Loïs Openda',      pos: 'FWD', club: 'RB Leipzig',          no: 21 },
    { id: 'be19', name: 'Koen Casteels',    pos: 'GK',  club: 'VfL Wolfsburg',       no: 12 },
  ]},
  uy: { name: 'Uruguay', flag: 'uy', players: [
    { id: 'uy1',  name: 'Sergio Rochet',    pos: 'GK',  club: 'Internacional',       no: 1  },
    { id: 'uy2',  name: 'Luis Suárez',      pos: 'FWD', club: 'Inter Miami',         no: 9  },
    { id: 'uy3',  name: 'Darwin Núñez',     pos: 'FWD', club: 'Liverpool',           no: 11 },
    { id: 'uy4',  name: 'Federico Valverde', pos: 'MID', club: 'Real Madrid',        no: 8  },
    { id: 'uy5',  name: 'Rodrigo Bentancur', pos: 'MID', club: 'Tottenham',          no: 6  },
    { id: 'uy6',  name: 'José María Giménez', pos: 'DEF', club: 'Atlético Madrid',   no: 2  },
    { id: 'uy7',  name: 'Diego Godín',      pos: 'DEF', club: 'Emretired',           no: 3  },
    { id: 'uy8',  name: 'Ronald Araújo',    pos: 'DEF', club: 'Barcelona',           no: 4  },
    { id: 'uy9',  name: 'Nicolás de la Cruz', pos: 'MID', club: 'Flamengo',          no: 10 },
    { id: 'uy10', name: 'Facundo Pellistri', pos: 'FWD', club: 'Manchester United',  no: 7  },
    { id: 'uy11', name: 'Matías Vecino',    pos: 'MID', club: 'Lazio',               no: 14 },
    { id: 'uy12', name: 'Giorgian de Arrascaeta', pos: 'MID', club: 'Flamengo',      no: 13 },
    { id: 'uy13', name: 'Edinson Cavani',   pos: 'FWD', club: 'Boca Juniors',        no: 21 },
    { id: 'uy14', name: 'Mathías Olivera',  pos: 'DEF', club: 'Napoli',              no: 16 },
    { id: 'uy15', name: 'Guillermo Varela', pos: 'DEF', club: 'Flamengo',            no: 17 },
    { id: 'uy16', name: 'Agustín Canobbio', pos: 'FWD', club: 'Atlético Paranaense', no: 18 },
    { id: 'uy17', name: 'Santiago Bueno',   pos: 'DEF', club: 'Wolves',              no: 5  },
  ]},
  co: { name: 'Kolombiya', flag: 'co', players: [
    { id: 'co1',  name: 'David Ospina',     pos: 'GK',  club: 'Al-Qadsiah',          no: 1  },
    { id: 'co2',  name: 'Luis Díaz',        pos: 'FWD', club: 'Liverpool',           no: 7  },
    { id: 'co3',  name: 'James Rodríguez',  pos: 'MID', club: 'Rayo Vallecano',      no: 10 },
    { id: 'co4',  name: 'Radamel Falcao',   pos: 'FWD', club: 'Emretired',           no: 9  },
    { id: 'co5',  name: 'Juan Cuadrado',    pos: 'MID', club: 'Juventus',            no: 11 },
    { id: 'co6',  name: 'Davinson Sánchez', pos: 'DEF', club: 'Galatasaray',         no: 2  },
    { id: 'co7',  name: 'Yerry Mina',       pos: 'DEF', club: 'Valencia',            no: 13 },
    { id: 'co8',  name: 'Wilmar Barrios',   pos: 'MID', club: 'Zenit',               no: 6  },
    { id: 'co9',  name: 'Mateus Uribe',     pos: 'MID', club: 'Porto',               no: 8  },
    { id: 'co10', name: 'Rafael Santos Borré', pos: 'FWD', club: 'Eintracht Frankfurt', no: 19 },
    { id: 'co11', name: 'Johan Mojica',     pos: 'DEF', club: 'Osasuna',             no: 3  },
    { id: 'co12', name: 'Daniel Muñoz',     pos: 'DEF', club: 'Crystal Palace',      no: 18 },
    { id: 'co13', name: 'Richard Ríos',     pos: 'MID', club: 'Palmeiras',           no: 16 },
    { id: 'co14', name: 'Jhon Córdoba',     pos: 'FWD', club: 'Krasnodar',           no: 22 },
  ]},
  us: { name: 'ABD', flag: 'us', players: [
    { id: 'us1',  name: 'Matt Turner',      pos: 'GK',  club: 'Nottingham Forest',   no: 1  },
    { id: 'us2',  name: 'Christian Pulisic', pos: 'FWD', club: 'AC Milan',           no: 10 },
    { id: 'us3',  name: 'Weston McKennie',  pos: 'MID', club: 'Juventus',            no: 8  },
    { id: 'us4',  name: 'Tyler Adams',      pos: 'MID', club: 'Bournemouth',         no: 4  },
    { id: 'us5',  name: 'Gio Reyna',        pos: 'MID', club: 'Borussia Dortmund',   no: 7  },
    { id: 'us6',  name: 'Tim Weah',         pos: 'FWD', club: 'Juventus',            no: 21 },
    { id: 'us7',  name: 'Josh Sargent',     pos: 'FWD', club: 'Norwich City',        no: 9  },
    { id: 'us8',  name: 'Ricardo Pepi',     pos: 'FWD', club: 'PSV Eindhoven',       no: 16 },
    { id: 'us9',  name: 'Sergiño Dest',     pos: 'DEF', club: 'PSV Eindhoven',       no: 2  },
    { id: 'us10', name: 'Walker Zimmerman', pos: 'DEF', club: 'Nashville SC',        no: 3  },
    { id: 'us11', name: 'Miles Robinson',   pos: 'DEF', club: 'Atlanta United',      no: 5  },
    { id: 'us12', name: 'Antonee Robinson', pos: 'DEF', club: 'Fulham',              no: 6  },
    { id: 'us13', name: 'Yunus Musah',      pos: 'MID', club: 'AC Milan',            no: 6  },
    { id: 'us14', name: 'Brenden Aaronson', pos: 'MID', club: 'Leeds United',        no: 11 },
    { id: 'us15', name: 'Folarin Balogun',  pos: 'FWD', club: 'Monaco',              no: 17 },
    { id: 'us16', name: 'Ethan Nwaneri',    pos: 'MID', club: 'Arsenal',             no: 19 },
    { id: 'us17', name: 'Zack Steffen',     pos: 'GK',  club: 'Colorado Rapids',     no: 12 },
  ]},
  mx: { name: 'Meksika', flag: 'mx', players: [
    { id: 'mx1',  name: 'Guillermo Ochoa',  pos: 'GK',  club: 'Salernitana',         no: 1  },
    { id: 'mx2',  name: 'Hirving Lozano',   pos: 'FWD', club: 'PSV Eindhoven',       no: 22 },
    { id: 'mx3',  name: 'Raúl Jiménez',     pos: 'FWD', club: 'Fulham',              no: 9  },
    { id: 'mx4',  name: 'Héctor Herrera',   pos: 'MID', club: 'Houston Dynamo',      no: 16 },
    { id: 'mx5',  name: 'Andrés Guardado',  pos: 'MID', club: 'Real Betis',          no: 18 },
    { id: 'mx6',  name: 'Carlos Vela',      pos: 'FWD', club: 'LAFC',                no: 11 },
    { id: 'mx7',  name: 'César Montes',     pos: 'DEF', club: 'Espanyol',            no: 3  },
    { id: 'mx8',  name: 'Edson Álvarez',    pos: 'MID', club: 'West Ham',            no: 4  },
    { id: 'mx9',  name: 'Jorge Sánchez',    pos: 'DEF', club: 'Ajax',                no: 2  },
    { id: 'mx10', name: 'Alexis Vega',      pos: 'FWD', club: 'Chivas',              no: 10 },
    { id: 'mx11', name: 'Luis Chávez',      pos: 'MID', club: 'Pachuca',             no: 14 },
    { id: 'mx12', name: 'Néstor Araujo',    pos: 'DEF', club: 'Celta Vigo',          no: 6  },
    { id: 'mx13', name: 'Héctor Moreno',    pos: 'DEF', club: 'Al-Gharafa',          no: 15 },
    { id: 'mx14', name: 'Roberto Alvarado', pos: 'MID', club: 'Chivas',              no: 8  },
    { id: 'mx15', name: 'Uriel Antuna',     pos: 'FWD', club: 'Cruz Azul',           no: 17 },
  ]},
  jp: { name: 'Japonya', flag: 'jp', players: [
    { id: 'jp1',  name: 'Shuichi Gonda',    pos: 'GK',  club: 'Shimizu S-Pulse',     no: 1  },
    { id: 'jp2',  name: 'Takehiro Tomiyasu', pos: 'DEF', club: 'Arsenal',            no: 5  },
    { id: 'jp3',  name: 'Takumi Minamino',  pos: 'FWD', club: 'Monaco',              no: 10 },
    { id: 'jp4',  name: 'Daichi Kamada',    pos: 'MID', club: 'Lazio',               no: 14 },
    { id: 'jp5',  name: 'Kaoru Mitoma',     pos: 'FWD', club: 'Brighton',            no: 11 },
    { id: 'jp6',  name: 'Ritsu Doan',       pos: 'FWD', club: 'Freiburg',            no: 21 },
    { id: 'jp7',  name: 'Wataru Endō',      pos: 'MID', club: 'Liverpool',           no: 6  },
    { id: 'jp8',  name: 'Maya Yoshida',     pos: 'DEF', club: 'Schalke 04',          no: 3  },
    { id: 'jp9',  name: 'Ko Itakura',       pos: 'DEF', club: 'Borussia M\'gladbach', no: 4 },
    { id: 'jp10', name: 'Hidemasa Morita',  pos: 'MID', club: 'Sporting CP',         no: 7  },
    { id: 'jp11', name: 'Ayase Ueda',       pos: 'FWD', club: 'Feyenoord',           no: 9  },
    { id: 'jp12', name: 'Yuki Soma',        pos: 'MID', club: 'Nagoya Grampus',      no: 8  },
    { id: 'jp13', name: 'Hiroki Sakai',     pos: 'DEF', club: 'Urawa Red Diamonds',  no: 2  },
    { id: 'jp14', name: 'Junya Ito',        pos: 'FWD', club: 'Reims',               no: 19 },
    { id: 'jp15', name: 'Ao Tanaka',        pos: 'MID', club: 'Fortuna Düsseldorf',  no: 16 },
    { id: 'jp16', name: 'Takuma Asano',     pos: 'FWD', club: 'Bochum',              no: 15 },
  ]},
  ma: { name: 'Fas', flag: 'ma', players: [
    { id: 'ma1',  name: 'Yassine Bounou',   pos: 'GK',  club: 'Al-Hilal',            no: 1  },
    { id: 'ma2',  name: 'Hakim Ziyech',     pos: 'MID', club: 'Galatasaray',         no: 7  },
    { id: 'ma3',  name: 'Youssef En-Nesyri', pos: 'FWD', club: 'Fenerbahçe',        no: 9  },
    { id: 'ma4',  name: 'Sofyan Amrabat',   pos: 'MID', club: 'Manchester United',   no: 4  },
    { id: 'ma5',  name: 'Achraf Hakimi',    pos: 'DEF', club: 'PSG',                 no: 2  },
    { id: 'ma6',  name: 'Romain Saïss',     pos: 'DEF', club: 'Beşiktaş',            no: 5  },
    { id: 'ma7',  name: 'Noussair Mazraoui', pos: 'DEF', club: 'Manchester United',  no: 3  },
    { id: 'ma8',  name: 'Azzedine Ounahi',  pos: 'MID', club: 'Marseille',           no: 8  },
    { id: 'ma9',  name: 'Selim Amallah',    pos: 'MID', club: 'Standard Liège',      no: 19 },
    { id: 'ma10', name: 'Jawad El Yamiq',   pos: 'DEF', club: 'Real Valladolid',     no: 6  },
    { id: 'ma11', name: 'Sofiane Boufal',   pos: 'FWD', club: 'Angers',              no: 11 },
    { id: 'ma12', name: 'Abdessamad Ezzalzouli', pos: 'FWD', club: 'Osasuna',        no: 17 },
    { id: 'ma13', name: 'Tarik Tissoudali', pos: 'FWD', club: 'Gent',               no: 21 },
    { id: 'ma14', name: 'Munir El Haddadi', pos: 'FWD', club: 'Almería',             no: 22 },
    { id: 'ma15', name: 'Yahia Attiyat Allah', pos: 'DEF', club: 'Wydad AC',         no: 22 },
  ]},
  sn: { name: 'Senegal', flag: 'sn', players: [
    { id: 'sn1',  name: 'Édouard Mendy',    pos: 'GK',  club: 'Chelsea',             no: 1  },
    { id: 'sn2',  name: 'Sadio Mané',       pos: 'FWD', club: 'Al-Nassr',            no: 10 },
    { id: 'sn3',  name: 'Kalidou Koulibaly', pos: 'DEF', club: 'Al-Hilal',           no: 3  },
    { id: 'sn4',  name: 'Idrissa Gueye',    pos: 'MID', club: 'Everton',             no: 6  },
    { id: 'sn5',  name: 'Cheikhou Kouyaté', pos: 'MID', club: 'Nottingham Forest',   no: 8  },
    { id: 'sn6',  name: 'Pape Matar Sarr',  pos: 'MID', club: 'Tottenham',           no: 7  },
    { id: 'sn7',  name: 'Ismaïla Sarr',     pos: 'FWD', club: 'Crystal Palace',      no: 19 },
    { id: 'sn8',  name: 'Boulaye Dia',      pos: 'FWD', club: 'Lazio',               no: 9  },
    { id: 'sn9',  name: 'Pathé Ciss',       pos: 'MID', club: 'Rayo Vallecano',      no: 17 },
    { id: 'sn10', name: 'Fodé Ballo-Touré', pos: 'DEF', club: 'AC Milan',            no: 5  },
    { id: 'sn11', name: 'Moussa Niakhaté',  pos: 'DEF', club: 'Nottingham Forest',   no: 4  },
    { id: 'sn12', name: 'Nicolas Jackson',  pos: 'FWD', club: 'Chelsea',             no: 11 },
    { id: 'sn13', name: 'Habib Diallo',     pos: 'FWD', club: 'Strasbourg',          no: 14 },
    { id: 'sn14', name: 'Krepin Diatta',    pos: 'FWD', club: 'Monaco',              no: 22 },
  ]},
  kr: { name: 'G. Kore', flag: 'kr', players: [
    { id: 'kr1',  name: 'Kim Seung-Gyu',    pos: 'GK',  club: 'Vissel Kobe',         no: 1  },
    { id: 'kr2',  name: 'Son Heung-Min',    pos: 'FWD', club: 'Tottenham',           no: 7  },
    { id: 'kr3',  name: 'Lee Kang-In',      pos: 'MID', club: 'PSG',                 no: 19 },
    { id: 'kr4',  name: 'Hwang Hee-Chan',   pos: 'FWD', club: 'Wolves',              no: 11 },
    { id: 'kr5',  name: 'Kim Min-Jae',      pos: 'DEF', club: 'Bayern München',      no: 3  },
    { id: 'kr6',  name: 'Jung Woo-Young',   pos: 'MID', club: 'Al-Qadsiah',          no: 6  },
    { id: 'kr7',  name: 'Hwang In-Beom',    pos: 'MID', club: 'Feyenoord',           no: 16 },
    { id: 'kr8',  name: 'Kim Jin-Su',       pos: 'DEF', club: 'Jeonbuk',             no: 14 },
    { id: 'kr9',  name: 'Kim Young-Gwon',   pos: 'DEF', club: 'Ulsan',               no: 19 },
    { id: 'kr10', name: 'Cho Gue-Sung',     pos: 'FWD', club: 'Jeonbuk',             no: 9  },
    { id: 'kr11', name: 'Na Sang-Ho',       pos: 'FWD', club: 'FC Seoul',            no: 17 },
    { id: 'kr12', name: 'Paik Seung-Ho',    pos: 'MID', club: 'Jeonbuk',             no: 8  },
    { id: 'kr13', name: 'Song Bum-Keun',    pos: 'GK',  club: 'Jeonbuk',             no: 21 },
    { id: 'kr14', name: 'Oh Hyeon-Gyu',     pos: 'FWD', club: 'Celtic',              no: 18 },
  ]},
  au: { name: 'Avustralya', flag: 'au', players: [
    { id: 'au1',  name: 'Mathew Ryan',      pos: 'GK',  club: 'Real Sociedad',       no: 1  },
    { id: 'au2',  name: 'Mathew Leckie',    pos: 'FWD', club: 'Melbourne City',      no: 7  },
    { id: 'au3',  name: 'Mitchell Duke',    pos: 'FWD', club: 'Fagiano Okayama',     no: 9  },
    { id: 'au4',  name: 'Martin Boyle',     pos: 'FWD', club: 'Hibernian',           no: 11 },
    { id: 'au5',  name: 'Aaron Mooy',       pos: 'MID', club: 'Celtic',              no: 13 },
    { id: 'au6',  name: 'Jackson Irvine',   pos: 'MID', club: 'St Pauli',            no: 8  },
    { id: 'au7',  name: 'Ajdin Hrustić',    pos: 'MID', club: 'Verona',              no: 10 },
    { id: 'au8',  name: 'Harry Souttar',    pos: 'DEF', club: 'Stoke City',          no: 3  },
    { id: 'au9',  name: 'Miloš Degenek',    pos: 'DEF', club: 'Columbus Crew',       no: 2  },
    { id: 'au10', name: 'Nathaniel Atkinson', pos: 'DEF', club: 'Hearts',            no: 4  },
    { id: 'au11', name: 'Keanu Baccus',     pos: 'MID', club: 'St Mirren',           no: 14 },
    { id: 'au12', name: 'Riley McGree',     pos: 'MID', club: 'Middlesbrough',       no: 6  },
    { id: 'au13', name: 'Craig Goodwin',    pos: 'FWD', club: 'Adelaide United',     no: 19 },
    { id: 'au14', name: 'Jordan Bos',       pos: 'DEF', club: 'Fortuna Sittard',     no: 5  },
  ]},
  ca: { name: 'Kanada', flag: 'ca', players: [
    { id: 'ca1',  name: 'Milan Borjan',     pos: 'GK',  club: 'Red Star Belgrade',   no: 18 },
    { id: 'ca2',  name: 'Alphonso Davies', pos: 'DEF', club: 'Bayern München',       no: 3  },
    { id: 'ca3',  name: 'Jonathan David',   pos: 'FWD', club: 'LOSC Lille',          no: 9  },
    { id: 'ca4',  name: 'Tajon Buchanan',   pos: 'FWD', club: 'Club Brugge',         no: 11 },
    { id: 'ca5',  name: 'Cyle Larin',       pos: 'FWD', club: 'Club Brugge',         no: 7  },
    { id: 'ca6',  name: 'Atiba Hutchinson', pos: 'MID', club: 'Beşiktaş',            no: 13 },
    { id: 'ca7',  name: 'Stephen Eustaquio', pos: 'MID', club: 'Porto',              no: 7  },
    { id: 'ca8',  name: 'Mark-Anthony Kaye', pos: 'MID', club: 'Club Brugge',        no: 8  },
    { id: 'ca9',  name: 'Richie Laryea',    pos: 'DEF', club: 'Nottingham Forest',   no: 19 },
    { id: 'ca10', name: 'Kamal Miller',     pos: 'DEF', club: 'Portland Timbers',    no: 5  },
    { id: 'ca11', name: 'Steven Vitória',   pos: 'DEF', club: 'Marítimo',            no: 4  },
    { id: 'ca12', name: 'Junior Hoilett',   pos: 'FWD', club: 'Cardiff City',        no: 10 },
    { id: 'ca13', name: 'Liam Millar',      pos: 'FWD', club: 'Basel',               no: 21 },
  ]},
  ch: { name: 'İsviçre', flag: 'ch', players: [
    { id: 'ch1',  name: 'Yann Sommer',      pos: 'GK',  club: 'Inter Milan',         no: 1  },
    { id: 'ch2',  name: 'Granit Xhaka',     pos: 'MID', club: 'Bayer Leverkusen',    no: 10 },
    { id: 'ch3',  name: 'Xherdan Shaqiri',  pos: 'FWD', club: 'Chicago Fire',        no: 23 },
    { id: 'ch4',  name: 'Haris Seferović',  pos: 'FWD', club: 'Galatasaray',         no: 9  },
    { id: 'ch5',  name: 'Manuel Akanji',    pos: 'DEF', club: 'Manchester City',     no: 5  },
    { id: 'ch6',  name: 'Nico Elvedi',      pos: 'DEF', club: 'Borussia M\'gladbach', no: 20 },
    { id: 'ch7',  name: 'Remo Freuler',     pos: 'MID', club: 'Nottingham Forest',   no: 8  },
    { id: 'ch8',  name: 'Denis Zakaria',    pos: 'MID', club: 'Juventus',            no: 16 },
    { id: 'ch9',  name: 'Ruben Vargas',     pos: 'FWD', club: 'Augsburg',            no: 11 },
    { id: 'ch10', name: 'Silvan Widmer',    pos: 'DEF', club: 'Mainz',               no: 3  },
    { id: 'ch11', name: 'Ricardo Rodriguez', pos: 'DEF', club: 'Torino',             no: 13 },
    { id: 'ch12', name: 'Fabian Rieder',    pos: 'MID', club: 'Rennes',              no: 17 },
    { id: 'ch13', name: 'Kwadwo Duah',      pos: 'FWD', club: 'Nuremberg',           no: 19 },
    { id: 'ch14', name: 'Zeki Amdouni',     pos: 'FWD', club: 'Burnley',             no: 21 },
    { id: 'ch15', name: 'Fabian Schär',     pos: 'DEF', club: 'Newcastle',           no: 4  },
  ]},
  pl: { name: 'Polonya', flag: 'pl', players: [
    { id: 'pl1',  name: 'Wojciech Szczęsny', pos: 'GK', club: 'Barcelona',           no: 1  },
    { id: 'pl2',  name: 'Robert Lewandowski', pos: 'FWD', club: 'Barcelona',         no: 9  },
    { id: 'pl3',  name: 'Piotr Zieliński',  pos: 'MID', club: 'Napoli',              no: 10 },
    { id: 'pl4',  name: 'Arkadiusz Milik',  pos: 'FWD', club: 'Juventus',            no: 7  },
    { id: 'pl5',  name: 'Grzegorz Krychowiak', pos: 'MID', club: 'Al-Shabab',        no: 6  },
    { id: 'pl6',  name: 'Kamil Glik',       pos: 'DEF', club: 'Benevento',           no: 15 },
    { id: 'pl7',  name: 'Matty Cash',       pos: 'DEF', club: 'Aston Villa',         no: 2  },
    { id: 'pl8',  name: 'Bartosz Bereszyński', pos: 'DEF', club: 'Sampdoria',        no: 3  },
    { id: 'pl9',  name: 'Jakub Moder',      pos: 'MID', club: 'Brighton',            no: 14 },
    { id: 'pl10', name: 'Krzysztof Piątek', pos: 'FWD', club: 'Salernitana',         no: 11 },
    { id: 'pl11', name: 'Nicola Zalewski',  pos: 'MID', club: 'Roma',                no: 17 },
    { id: 'pl12', name: 'Damian Szymański', pos: 'MID', club: 'AEK Athens',          no: 19 },
    { id: 'pl13', name: 'Sebastian Szymański', pos: 'MID', club: 'Fenerbahçe',       no: 13 },
    { id: 'pl14', name: 'Paweł Dawidowicz', pos: 'DEF', club: 'Verona',              no: 5  },
  ]},
  rs: { name: 'Sırbistan', flag: 'rs', players: [
    { id: 'rs1',  name: 'Predrag Rajković', pos: 'GK',  club: 'Mallorca',            no: 1  },
    { id: 'rs2',  name: 'Aleksandar Mitrović', pos: 'FWD', club: 'Al-Hilal',        no: 9  },
    { id: 'rs3',  name: 'Dušan Vlahović',   pos: 'FWD', club: 'Juventus',           no: 11 },
    { id: 'rs4',  name: 'Sergej Milinković-Savić', pos: 'MID', club: 'Al-Hilal',    no: 11 },
    { id: 'rs5',  name: 'Dušan Tadić',      pos: 'FWD', club: 'Fenerbahçe',          no: 10 },
    { id: 'rs6',  name: 'Nemanja Gudelj',   pos: 'MID', club: 'Sevilla',             no: 8  },
    { id: 'rs7',  name: 'Nikola Milenković', pos: 'DEF', club: 'Nottingham Forest',  no: 4  },
    { id: 'rs8',  name: 'Strahinja Pavlović', pos: 'DEF', club: 'RB Salzburg',       no: 5  },
    { id: 'rs9',  name: 'Filip Kostić',     pos: 'MID', club: 'Juventus',            no: 7  },
    { id: 'rs10', name: 'Andrija Živković', pos: 'MID', club: 'PAOK',               no: 17 },
    { id: 'rs11', name: 'Sasa Lukić',       pos: 'MID', club: 'Fulham',              no: 14 },
    { id: 'rs12', name: 'Luka Jović',       pos: 'FWD', club: 'AC Milan',            no: 18 },
    { id: 'rs13', name: 'Ivan Ilić',        pos: 'MID', club: 'Verona',              no: 16 },
    { id: 'rs14', name: 'Strahinja Eraković', pos: 'DEF', club: 'Red Star Belgrade', no: 3  },
  ]},
  gh: { name: 'Gana', flag: 'gh', players: [
    { id: 'gh1',  name: 'Lawrence Ati-Zigi', pos: 'GK', club: 'St Gallen',           no: 1  },
    { id: 'gh2',  name: 'Thomas Partey',    pos: 'MID', club: 'Arsenal',             no: 5  },
    { id: 'gh3',  name: 'Jordan Ayew',      pos: 'FWD', club: 'Crystal Palace',      no: 10 },
    { id: 'gh4',  name: 'André Ayew',       pos: 'FWD', club: 'Al-Qadsiah',          no: 11 },
    { id: 'gh5',  name: 'Mohammed Salisu',  pos: 'DEF', club: 'Southampton',         no: 4  },
    { id: 'gh6',  name: 'Alexander Djiku',  pos: 'DEF', club: 'Strasbourg',          no: 3  },
    { id: 'gh7',  name: 'Daniel-Kofi Kyereh', pos: 'MID', club: 'Freiburg',          no: 7  },
    { id: 'gh8',  name: 'Kamaldeen Sulemana', pos: 'FWD', club: 'Rennes',            no: 17 },
    { id: 'gh9',  name: 'Abdul Fatawu',     pos: 'FWD', club: 'Leicester City',      no: 21 },
    { id: 'gh10', name: 'Elisha Owusu',     pos: 'MID', club: 'Gent',               no: 8  },
    { id: 'gh11', name: 'Tariq Lamptey',    pos: 'DEF', club: 'Brighton',            no: 2  },
    { id: 'gh12', name: 'Baba Rahman',      pos: 'DEF', club: 'Reading',             no: 13 },
    { id: 'gh13', name: 'Antoine Semenyo',  pos: 'FWD', club: 'Bournemouth',         no: 19 },
  ]},
  ci: { name: 'Fildişi Sahili', flag: 'ci', players: [
    { id: 'ci1',  name: 'Yahia Fofana',     pos: 'GK',  club: 'Leicester City',      no: 1  },
    { id: 'ci2',  name: 'Sébastien Haller', pos: 'FWD', club: 'Borussia Dortmund',   no: 9  },
    { id: 'ci3',  name: 'Franck Kessié',    pos: 'MID', club: 'Barcelona',           no: 5  },
    { id: 'ci4',  name: 'Serge Aurier',     pos: 'DEF', club: 'Nottingham Forest',   no: 2  },
    { id: 'ci5',  name: 'Nicolas Pépé',     pos: 'FWD', club: 'Nice',                no: 19 },
    { id: 'ci6',  name: 'Wilfried Zaha',    pos: 'FWD', club: 'Crystal Palace',      no: 11 },
    { id: 'ci7',  name: 'Max-Alain Gradel', pos: 'FWD', club: 'Al-Ahli',             no: 21 },
    { id: 'ci8',  name: 'Cheick Tioté',     pos: 'MID', club: 'Retired',             no: 8  },
    { id: 'ci9',  name: 'Jean-Michaël Seri', pos: 'MID', club: 'Hull City',          no: 6  },
    { id: 'ci10', name: 'Willy Boly',       pos: 'DEF', club: 'Nottingham Forest',   no: 4  },
    { id: 'ci11', name: 'Eric Bailly',      pos: 'DEF', club: 'Besiktas',            no: 3  },
    { id: 'ci12', name: 'Odilon Kossounou', pos: 'DEF', club: 'Bayer Leverkusen',    no: 14 },
    { id: 'ci13', name: 'Simon Adingra',    pos: 'FWD', club: 'Brighton',            no: 17 },
  ]},
  cm: { name: 'Kamerun', flag: 'cm', players: [
    { id: 'cm1',  name: 'André Onana',      pos: 'GK',  club: 'Manchester United',   no: 1  },
    { id: 'cm2',  name: 'Vincent Aboubakar', pos: 'FWD', club: 'Al-Qadsiah',         no: 10 },
    { id: 'cm3',  name: 'Karl Toko Ekambi', pos: 'FWD', club: 'Lyon',                no: 9  },
    { id: 'cm4',  name: 'Bryan Mbeumo',     pos: 'FWD', club: 'Brentford',           no: 11 },
    { id: 'cm5',  name: 'Jean-Charles Castelletto', pos: 'DEF', club: 'Nantes',      no: 5  },
    { id: 'cm6',  name: 'Collins Fai',      pos: 'DEF', club: 'Standard Liège',      no: 2  },
    { id: 'cm7',  name: 'Nicolas Nkoulou',  pos: 'DEF', club: 'Torino',              no: 4  },
    { id: 'cm8',  name: 'Martin Hongla',    pos: 'MID', club: 'Hellas Verona',       no: 6  },
    { id: 'cm9',  name: 'Pierre Kunde',     pos: 'MID', club: 'Osasuna',             no: 8  },
    { id: 'cm10', name: 'Samuel Oum Gouet', pos: 'MID', club: 'Mechelen',            no: 17 },
    { id: 'cm11', name: 'Clinton Njie',     pos: 'FWD', club: 'Marseille',           no: 7  },
    { id: 'cm12', name: 'Stéphane Bahoken', pos: 'FWD', club: 'Angers',              no: 19 },
    { id: 'cm13', name: 'Harold Moukoudi',  pos: 'DEF', club: 'Saint-Étienne',       no: 3  },
  ]},
  sa: { name: 'S. Arabistan', flag: 'sa', players: [
    { id: 'sa1',  name: 'Mohammed Al-Owais', pos: 'GK', club: 'Al-Hilal',            no: 1  },
    { id: 'sa2',  name: 'Salem Al-Dawsari', pos: 'FWD', club: 'Al-Hilal',            no: 10 },
    { id: 'sa3',  name: 'Mohammed Al-Shehri', pos: 'FWD', club: 'Al-Hilal',          no: 9  },
    { id: 'sa4',  name: 'Saleh Al-Shehri',  pos: 'FWD', club: 'Al-Fayha',            no: 11 },
    { id: 'sa5',  name: 'Ali Al-Bulaihi',   pos: 'DEF', club: 'Al-Hilal',            no: 4  },
    { id: 'sa6',  name: 'Yasser Al-Shahrani', pos: 'DEF', club: 'Al-Hilal',          no: 3  },
    { id: 'sa7',  name: 'Abdulelah Al-Malki', pos: 'MID', club: 'Al-Shabab',         no: 7  },
    { id: 'sa8',  name: 'Sami Al-Najei',    pos: 'MID', club: 'Al-Qadsiah',          no: 8  },
    { id: 'sa9',  name: 'Ali Al-Hassan',    pos: 'MID', club: 'Al-Hilal',            no: 13 },
    { id: 'sa10', name: 'Mohamed Kanno',    pos: 'MID', club: 'Al-Shabab',           no: 17 },
    { id: 'sa11', name: 'Hattan Bahbir',    pos: 'FWD', club: 'Al-Hilal',            no: 19 },
    { id: 'sa12', name: 'Ahmad Al-Ghamdi',  pos: 'DEF', club: 'Al-Batin',            no: 5  },
    { id: 'sa13', name: 'Sultan Al-Ghannam', pos: 'GK', club: 'Al-Nassr',            no: 12 },
  ]},
  ir: { name: 'İran', flag: 'ir', players: [
    { id: 'ir1',  name: 'Alireza Beiranvand', pos: 'GK', club: 'Antwerp',            no: 1  },
    { id: 'ir2',  name: 'Sardar Azmoun',    pos: 'FWD', club: 'Roma',                no: 9  },
    { id: 'ir3',  name: 'Mehdi Taremi',     pos: 'FWD', club: 'Inter Milan',         no: 9  },
    { id: 'ir4',  name: 'Alireza Jahanbakhsh', pos: 'FWD', club: 'Feyenoord',        no: 7  },
    { id: 'ir5',  name: 'Ehsan Hajsafi',    pos: 'DEF', club: 'AEK Athens',          no: 3  },
    { id: 'ir6',  name: 'Majid Hosseini',   pos: 'DEF', club: 'Kasımpaşa',           no: 4  },
    { id: 'ir7',  name: 'Saeid Ezatolahi',  pos: 'MID', club: 'Nottingham Forest',   no: 6  },
    { id: 'ir8',  name: 'Ramin Rezaeian',   pos: 'DEF', club: 'Kortrijk',            no: 2  },
    { id: 'ir9',  name: 'Saman Ghoddos',    pos: 'MID', club: 'Brentford',           no: 10 },
    { id: 'ir10', name: 'Ali Gholizadeh',   pos: 'FWD', club: 'Charleroi',           no: 11 },
    { id: 'ir11', name: 'Ahmad Noorollahi', pos: 'MID', club: 'Persepolis',          no: 8  },
    { id: 'ir12', name: 'Milad Mohammadi',  pos: 'DEF', club: 'AEK Athens',          no: 5  },
    { id: 'ir13', name: 'Kaveh Rezaei',     pos: 'FWD', club: 'Club Brugge',         no: 17 },
  ]},
  ec: { name: 'Ekvador', flag: 'ec', players: [
    { id: 'ec1',  name: 'Hernán Galíndez',  pos: 'GK',  club: 'Aucas',               no: 1  },
    { id: 'ec2',  name: 'Enner Valencia',   pos: 'FWD', club: 'Fenerbahçe',          no: 13 },
    { id: 'ec3',  name: 'Moisés Caicedo',   pos: 'MID', club: 'Chelsea',             no: 25 },
    { id: 'ec4',  name: 'Pervis Estupiñán', pos: 'DEF', club: 'Brighton',            no: 3  },
    { id: 'ec5',  name: 'Piero Hincapié',   pos: 'DEF', club: 'Bayer Leverkusen',    no: 4  },
    { id: 'ec6',  name: 'Ángel Mena',       pos: 'FWD', club: 'León',                no: 11 },
    { id: 'ec7',  name: 'Jhegson Méndez',   pos: 'MID', club: 'Los Angeles FC',      no: 6  },
    { id: 'ec8',  name: 'Jeremy Sarmiento', pos: 'FWD', club: 'Brighton',            no: 17 },
    { id: 'ec9',  name: 'Gonzalo Plata',    pos: 'FWD', club: 'Sporting CP',         no: 7  },
    { id: 'ec10', name: 'José Cifuentes',   pos: 'MID', club: 'Los Angeles FC',      no: 8  },
    { id: 'ec11', name: 'Angelo Preciado',  pos: 'DEF', club: 'Genk',                no: 2  },
    { id: 'ec12', name: 'Robert Arboleda',  pos: 'DEF', club: 'São Paulo',           no: 5  },
    { id: 'ec13', name: 'Kevin Rodríguez',  pos: 'MID', club: 'Ipswich Town',        no: 16 },
  ]},
  qa: { name: 'Katar', flag: 'qa', players: [
    { id: 'qa1',  name: 'Meshaal Barsham',  pos: 'GK',  club: 'Al-Sadd',             no: 1  },
    { id: 'qa2',  name: 'Akram Afif',       pos: 'FWD', club: 'Al-Sadd',             no: 11 },
    { id: 'qa3',  name: 'Almoez Ali',       pos: 'FWD', club: 'Al-Duhail',           no: 19 },
    { id: 'qa4',  name: 'Assim Madibo',     pos: 'MID', club: 'Al-Sadd',             no: 5  },
    { id: 'qa5',  name: 'Abdelkarim Hassan', pos: 'DEF', club: 'Al-Sadd',            no: 3  },
    { id: 'qa6',  name: 'Pedro Miguel',     pos: 'DEF', club: 'Al-Sadd',             no: 2  },
    { id: 'qa7',  name: 'Bassam Al-Rawi',   pos: 'DEF', club: 'Al-Gharafa',          no: 6  },
    { id: 'qa8',  name: 'Hassan Al-Haydos', pos: 'MID', club: 'Al-Sadd',             no: 10 },
    { id: 'qa9',  name: 'Karim Boudiaf',    pos: 'MID', club: 'Al-Duhail',           no: 8  },
    { id: 'qa10', name: 'Homam Ahmed',      pos: 'MID', club: 'Al-Wakrah',           no: 14 },
    { id: 'qa11', name: 'Yusuf Abdurisag',  pos: 'FWD', club: 'Al-Sadd',             no: 9  },
    { id: 'qa12', name: 'Boualem Khoukhi',  pos: 'DEF', club: 'Al-Sadd',             no: 4  },
    { id: 'qa13', name: 'Mohammed Waad',    pos: 'DEF', club: 'Al-Ahli',             no: 7  },
  ]},
};
